apiVersion: apps/v1
kind: Deployment 
metadata:
  name: <PROJECT_NAME>
  namespace: <ENV>-app
  labels:
    app: <PROJECT_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <PROJECT_NAME>
  template:
    metadata:
      labels:
        app: <PROJECT_NAME>
    spec:
      containers:
      - name: app-<PROJECT_NAME>
        image: <BUILD_NAME>:<BUILD_TAG>
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - "mkdir /data/logs/<PROJECT_NAME> /data/web/<PROJECT_NAME> -p;chown -R nginx.nginx /data"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data/logs/<PROJECT_NAME>
          name: web-log
        - mountPath: /etc/nginx/conf.d/
          name: www-conf
          readOnly: true
      volumes: 
      - name: web-log
        hostPath:
          path: /data/logs/<PROJECT_NAME>
      - name: www-conf
        configMap:
          name: www-conf
      imagePullSecrets:
      - name: registry
